dist: bionic

language: minimal

install:
  - curl -fsSL https://get.docksal.io | bash
  - fin version
  - fin sysinfo

before_script:
  - fin init
  - fin exec 'sudo composer self-update'

script:
  - fin rebuild-test
