version: "3.8"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  web:
    build: "./.docker/web"
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    restart: always
    networks:
      - frontend
      - backend
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
    networks:
      - backend

  pma:
    image: arm64v8/phpmyadmin
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_PORT=${MYSQL_PORT}
      - PMA_ARBITRARY=0
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_USER_PASSWORD}
    restart: always
    ports:
      - 81:80
    depends_on:
      - db
    networks:
      - frontend
      - backend

