<?php

/**
 * @file
 * Popular search keywords module.
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\search_api\Query\QueryInterface;

/**
 * Alter a search query before it gets executed.
 *
 * The hook is invoked after all enabled processors have preprocessed the query.
 *
 * @param \Drupal\search_api\Query\QueryInterface $query
 *   The query that will be executed.
 */
function popular_search_keywords_search_api_query_alter(QueryInterface &$query) {
  $user = Drupal::currentUser();
  $language = Drupal::languageManager()->getCurrentLanguage();
  $database = Database::getConnection();
  $index = $query->getIndex();
  if (!empty($index)) {
    $server = $index->get('server');
  }

  if (empty($index) || empty($server)) {
    return;
  }

  $originalKeys = $query->getOriginalKeys();
  if (is_array($originalKeys)) {
    // Handle the case when getOriginalKeys() returns an array.
    foreach ($originalKeys as $value) {
      // Trim each keyword individually.
      $keywords = trim(mb_strtolower($value));
    }
  }
  elseif (is_string($originalKeys)) {
    // Handle the case when getOriginalKeys() returns a string.
    $keywords = trim(mb_strtolower($originalKeys));
  }
  else {
    // Handle the case when getOriginalKeys() returns null.
    $keywords = '';
  }
  // To avoid to insert empty keywords value into database.
  if (!empty($keywords)) {
    $database->insert('popular_search')->fields(
      [
        's_name' => $server,
        'i_name' => $index->id(),
        'timestamp' => \Drupal::time()->getRequestTime(),
        'uid' => $user->id(),
        'sid' => session_id(),
        'keywords' => $keywords,
        'filters' => '',
        'sort' => '',
        'language' => $language->getId(),
      ]
    )->execute();
  }
}

/**
 * Implements hook_views_api().
 */
function popular_search_keywords_views_api() {
  return [
    'api' => 3.0,
    'path' => \Drupal::service('extension.list.module')->getPath('popular_search_keywords') . '/includes/views',
  ];
}

/**
 * Implements hook_theme().
 */
function popular_search_keywords_theme($existing, $type, $theme, $path) {

  return [
    'popular_search_keywords_block' => [
      'variables' => [
        'path' => '',
        'param_name' => '',
        'hide_search_count' => FALSE,
        'stats' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_help().
 */
function popular_search_keywords_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the popular_search_keywords module.
    case 'help.page.popular_search_keywords':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides a block with a list of the popular search keywords in the site.') . '</p>';
      return $output;

    default:
  }

}
