<?php


use Drupal\bc_utiltiy\Controller\OldContentNotify;

/**
 * @file
 * Implementing custom hook functions
 */
function bc_utility_cron()
{
  \Drupal::logger('bc_utility')->notice('bellcom utility cron start');

//  OldContentNotify::handler();

  \Drupal::logger('bc_utility')->notice('bellcom utility cron done');
}

function bc_utility_mail($key, &$message, $params)
{
  if ($key === 'old_article')
  {
    if (isset($params['headers']))
    {
      $message['headers'] = array_merge($message['headers'], $params['headers']);
    }

    $message['from'] = $params['from'];
    $message['subject'] = t($params['subject']);
    $message['body'][] = $params['body'];

    \Drupal::logger('bc_utility')->notice('mail hook key ' . print_r( $message , true));

  }
}
