<?php

use Drupal\bc_utility\Controller\OldContentNotity;
use Drupal\bc_utility\Plugin\Widgets\LinkWidgetValidators;
use Drupal\Component\Render\FormattableMarkup;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Form\FormStateInterface;
use Drupal\search_api\Query\QueryInterface;
use Drupal\Core\Database\Database;
use Drupal\Core\Session\AccountInterface;



/**
 * @file
 * Implementing custom hook functions
 */
function bc_utility_cron()
{


}

function bc_utility_mail($key, &$message, $params)
{
  if ($key === 'old_article')
  {
    if (isset($params['headers']))
    {
      $message['headers'] = array_merge($message['headers'], $params['headers']);
    }

    $message['from'] = $params['from'];
    $message['subject'] = t($params['subject']);
    $message['body'][] = new FormattableMarkup($params['body'], []);
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 *
 * Hide External link block if Internal links are exists
 */
function bc_utility_block_access($block, $operation, $account) {
  if ($operation == 'view') {
    if ($block->get('id') == 'fds_faxe_theme_indholdfield_ext_links'){
      $node = \Drupal::routeMatch()->getParameter('node');
      if($node && $node->hasField('field_link_til_andet_indhold')) {
        if (!empty($node->field_link_til_andet_indhold->getValue())) {
          return AccessResult::forbidden();
        }
      }
    }
  }
  return AccessResult::neutral();
}

function bc_utility_field_widget_single_element_form_alter(array &$element, FormStateInterface $form_state, array $context) {
  if (isset($element['uri'])) {
    $element['uri']['#element_validate'] = [[LinkWidgetValidators::class, 'validateUriElement']];
  }
}


function bc_utility_search_api_query_alter(QueryInterface &$query)
{
  $index = $query->getIndex();

  if (!empty($index)) {
    $server = $index->get('server');
  }

  if (empty($index) || empty($server)) {
    return;
  }

  $originalKeys = $query->getOriginalKeys() ?? '';
  $lowerOriginalKeys = mb_strtolower($originalKeys);
  $keywords = trim($lowerOriginalKeys);

  if (!empty($keywords)) {
    if (!preg_match('/^[a-zA-Z0-9æøåÆØÅ,\s-]+$/', $keywords) || strlen($keywords) < 3 || strlen($keywords) > 50) {
        $query->keys("");
    }
  }

}

/**
 * Convert user name to full name on ringsted portal
 *
 * @param $name
 * @param \Drupal\Core\Session\AccountInterface $account
 *
 * @return void
 */
function bc_utility_user_format_name_alter(&$name, AccountInterface $account) {
  $teamName = \Drupal::service('theme.manager')->getActiveTheme()->getName();
  if ($teamName == 'fds_portal_ringsted_theme') {
    if (!empty($account->field_full_name) && !empty($account->field_full_name->value)) {
      $name = $account->field_full_name->value;
    }
  }
}

function bc_utility_preprocess_status_messages(&$variables) {

  if (isset($variables['message_list'])) {

    $config = \Drupal::config('bc_utility_status_messages.settings');

    if (isset($variables['message_list']['status']) && $config->get('status')) {
      unset( $variables['message_list']['status'] );
    }

    if (isset($variables['message_list']['warning']) && $config->get('warning')) {
      unset( $variables['message_list']['warning'] );
    }

    if (isset($variables['message_list']['error'])  && $config->get('error')) {
      unset( $variables['message_list']['error'] );
    }

  }
}

// kontekstuelle filtre
// We pass the user ID as the Entity ID.

// Forbindelser
// OG membership: Group Indholdselement from OG membership
