<?php

use Drupal\bc_utility\Controller\OldContentNotity;
use Drupal\Component\Render\FormattableMarkup;

/**
 * @file
 * Implementing custom hook functions
 */
function bc_utility_cron()
{
  $run = FALSE;
  $last_start = \Drupal::keyValue('bc_utility_cron')->get('last_start');
  if (empty($last_start)) {
    $run = TRUE;
  } else {
    $datediff = time() - $last_start;
    $daysDiff = round($datediff / (60 * 60 * 24));
    // If last run was 30 day ago or more.
    if ($daysDiff >= 30) {
      $run = TRUE;
    }
  }

  if ($run) {
    Drupal::logger('bc_utility')->info("bc utility cron run");
    \Drupal::keyValue('bc_utility_cron')->set('last_start', time());
    OldContentNotity::handler();
  }
}

function bc_utility_mail($key, &$message, $params)
{
  if ($key === 'old_article')
  {
    if (isset($params['headers']))
    {
      $message['headers'] = array_merge($message['headers'], $params['headers']);
    }

    $message['from'] = $params['from'];
    $message['subject'] = t($params['subject']);
    $message['body'][] = new FormattableMarkup($params['body'], []);
  }
}
