version: "2.1"
services:
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail
  # PHPMyAdmin
  pma:
    hostname: pma
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    labels:
      - io.docksal.virtual-host=pma.${VIRTUAL_HOST}
#  solr:
#    image: docksal/solr:7.5-edge
#    volumes:
#      - ${PROJECT_ROOT}/.docksal/etc/solr/conf:/var/lib/solr/conf:ro
#    extends:
#      file: ${HOME}/.docksal/stacks/services.yml
#      service: solr
#    labels:
#      - 'io.docksal.virtual-host=solr.${VIRTUAL_HOST}'


#  blackfire:
#    extends:
#      file: ${HOME}/.docksal/stacks/services.yml
#      service: blackfire
#    environment:
#      - BLACKFIRE_LOG_LEVEL=4
#
#  memcached:
#    extends:
#      file: ${HOME}/.docksal/stacks/services.yml
#      service: memcached
