<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_preprocess_page().
 */
function fds_bcdagsorden_theme_preprocess_page(array &$variables)
{

  $variables['theme_settings'] = _fds_base_theme_collect_theme_settings();

  $logo = theme_get_setting('logo');
  if (!empty( $logo ) && !empty($logo['url']))
  {
    $variables['custom_logo'] = $logo['url'];
  }

}

/**
 * Implements hook_form_search_block_form_alter().
 */
function fds_bcdagsorden_theme_form_search_block_form_alter(&$form, FormStateInterface $form_state) {
  $form['keys']['#attributes']['placeholder'] = t('Find hvad du leder efter');
}

/**
 * Implements hook_form_search_form_alter().
 */
function fds_bcdagsorden_theme_form_search_form_alter(&$form, FormStateInterface $form_state) {
  $form['basic']['label'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['search-form-label'],
    ],
    'markup' => ['#markup' => $form['basic']['keys']['#title']->render()],
  ];
  $form['basic']['keys']['#title'] = '';
  $form['basic']['#attributes'] = [];
  $form['basic']['search-line'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['container-inline'],
    ],
    'keys' => $form['basic']['keys'],
    'submit' => $form['basic']['submit'],
  ];

  unset($form['basic']['keys']);
  unset($form['basic']['submit']);
}

/**
 * Implements template_preprocess_swiftmailer().
 */
function fds_bcdagsorden_theme_preprocess_swiftmailer(&$variables) {
  global $base_url;
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $theme = \Drupal::theme()->getActiveTheme();
  $theme_path = $base_url . '/' . $theme->getPath();

  // Theme settings.
  $theme_settings = _fds_base_theme_collect_theme_settings();
  $variables['current_language'] = $language;
  $variables['base_url'] = $GLOBALS['base_url'] . '/';
  $variables['logo_url'] = $theme_path . '/dist/images/logo--mail.svg';
  $variables['theme_settings'] = $theme_settings;

  // Header logo.
  if (!empty($theme_settings['language_logo']['header_logo__' . $language])) {
    $file = File::load($theme_settings['language_logo']['header_logo__' . $language]);
    if (!empty($file)) {
      $variables['logo_url'] = file_create_url($file->getFileUri());
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function fds_bcdagsorden_theme_preprocess_anonymous_subscriptions_message(array &$variables) {
  $subscription = $variables['subscription'];
  if (!empty($subscription->type->value) && $subscription->type->value == 'os2web_hearings_hearing_case') {
    $variables['link'] = Link::fromTextAndUrl(t('Klik her for at gå til høringer og afgørelser'), Url::fromUserInput('/hoeringer-og-afgoerelser'));
  }
}

/**
 * Implements hook_preprocess_term().
 */
function fds_bcdagsorden_theme_preprocess_taxonomy_term(array &$variables) {
  /** @var \Drupal\taxonomy\TermInterface $term */
  $term = $variables['term'];

  if ($variables['view_mode'] == 'full' && $term->bundle() == 'os2web_sektion') {
    // Get all pages that are using this section and are promoted.
    $entity_ids = getSectionPromotedNodes($term->id());
    if (empty($entity_ids)) {
      return;
    }

    $nodes = Node::loadMultiple($entity_ids);
    $promoted_node_links = [];

    /** @var \Drupal\node\NodeInterface $node */
    foreach ($nodes as $node) {
      $promoted_node_links[] = [
        'title' => $node->label(),
        'url' => $node->toUrl(),
      ];
    }

    $variables['#promoted_node_links'] = $promoted_node_links;
  }
}

/**
 * Implements hook_preprocess_node().
 */
function fds_bcdagsorden_theme_preprocess_node(array &$variables) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'];

  if (($variables['view_mode'] == 'search_result' || $variables['view_mode'] == 'search_index') && $node->getType() == 'os2web_page') {
    $sectionLabels = [];
    if ($section_id = $node->field_os2web_page_section->target_id) {
      $parents = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadAllParents($section_id);

      foreach ($parents as $parent) {
        $sectionLabels[] = $parent->label();
      }

      $variables['#section_labels'] = array_reverse($sectionLabels);
    }
  }
}

/**
 * Implements hook_preprocess_menu().
 */
function fds_bcdagsorden_theme_preprocess_menu(&$variables, $hook) {
  if ($hook == 'menu') {
    if (!empty($variables['attributes']['block'])) {
      unset($variables['attributes']['block']);
    }
  }
}

/**
 * Implements template_preprocess_symfony_mailer_lite_email().
 */
function fds_bcdagsorden_theme_preprocess_symfony_mailer_lite_email(&$variables) {
  global $base_url;
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $theme = \Drupal::theme()->getActiveTheme();
  $theme_path = $base_url . '/' . $theme->getPath();

  // Theme settings.
  $theme_settings = _fds_base_theme_collect_theme_settings();
  $variables['current_language'] = $language;
  $variables['base_url'] = $GLOBALS['base_url'] . '/';
  $variables['logo_url'] = $theme_path . '/dist/images/logo.png';
  $variables['theme_settings'] = $theme_settings;

  // Header logo.
  $logo = theme_get_setting('logo');
  if (!empty( $logo ) && !empty($logo['url'])) {
    $variables['logo_url'] = $GLOBALS['base_url'] . $logo['url'];
  }
}

function fds_bcdagsorden_theme_form_system_theme_settings_alter(&$form, &$form_state) {
  // Create a section for your link settings.
  $form['bcdagsorden_privacy'] = [
    '#type' => 'details',
    '#title' => t('Privatpolitik indstillinger'),
    '#open' => TRUE,
  ];

  // Add a URL field for the privacy policy link.
  $form['bcdagsorden_privacy']['privacy_policy_link'] = [
    '#type' => 'url',
    '#title' => t('Privatpolitik URL'),
    '#default_value' => theme_get_setting('privacy_policy_link'),
    '#description' => t('Indsæt det fulde link til privatpolitik (e.g., https://example.com/privacy).'),
  ];
}

function fds_bcdagsorden_theme_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'anonymous_subscription_taxonomy_terms_form') {
    if (isset($form['email'])) {
      $form['email']['#attributes']['placeholder'] = t('Indtast din e-mail...');
    }
     if (isset($form['op'])) {

          $form['op']['#weight'] = 40;
        }

    $owner_name = theme_get_setting('business_owner_name');
    $privacy_link = theme_get_setting('privacy_policy_link');

    $title_text = t('Jeg accepterer, at @owner_name indsamler og behandler persondata som beskrevet i <a href="@policy_link" target="_blank">vores politik om databeskyttelse.</a>',
              [
                '@owner_name' => $owner_name,
                '@policy_link' => $privacy_link,
              ],
              ['context' => 'default', 'html' => TRUE]
            );

            $form['terms_checkbox'] = [
              '#type' => 'checkbox',
              // Markup::create() ensures the string with <a> is interpreted as HTML.
              '#title' => Markup::create($title_text),
              '#required' => TRUE,
              '#weight' => 35,
            ];

                $form['#after_build'][] = 'fds_bcdagsorden_theme_after_build';


  }
}

function fds_bcdagsorden_theme_after_build($form, FormStateInterface $form_state) {
  // Only do this if both elements exist
  if (isset($form['terms_checkbox']) && isset($form['op'])) {

    // Save them in variables
    $checkbox = $form['terms_checkbox'];
    $submit = $form['op'];

    // Remove them from the form array
    unset($form['terms_checkbox']);
    unset($form['op']);

    // Re-insert them so checkbox is first
    $form['terms_checkbox'] = $checkbox;
    $form['op'] = $submit;
  }

  return $form;
}
