<?php


/**
 * Implements hook_form_alter().
 */

function rk_link_autocomplete_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $hide_links_path = '/hide-link-suggestions';  // Adjust this if your view's path is different.

  array_walk_recursive($form, function (&$element) use ($hide_links_path) {
    // Ensure $element is an array and has the expected properties.
    if (is_array($element) && isset($element['#autocomplete_route_name']) && $element['#autocomplete_route_name'] == 'entity.autocomplete') {
      $element['#autocomplete_route_path'] = $hide_links_path;
    }
  });
}
