version: '3.7'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local
services:

  # General application container.
  # Could be run with many replica on demand.
  php:
    # Both php and CLI containers should use the same container.
    image: dkbellcom/os2web-subsites:${TAG}
    volumes:
      - ./logs:/var/log:delegated
      - ./volumes/drupal/private:/opt/drupal/private
      - ./volumes/drupal/web/sites:/opt/drupal/web/sites
      - ./volumes/apache2/sites-available:/etc/apache2/sites-available
      - ./volumes/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./volumes/config:/opt/drupal/config
      - ./volumes/crontabs:/var/spool/cron/crontabs
      - ./volumes/tmp:/opt/drupal/tmp
      #- ../../scripts/os2subsites_provision:/opt/drupal/scripts/os2subsites_provision
    depends_on:
      - mariadb
    ports:
      - "${WEB_SERVER_PORT}:80"
    networks:
      - backend
      - frontend
    env_file:
      - .env

  mariadb:
    image: mariadb:latest
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend
    env_file:
      - .env
